#!/usr/bin/env python
# Build the unit tests

progs = []
progs.append (bld.program (
    source = bld.path.ant_glob ("juce/**/*.cpp"),
    includes = [ 'juce' ],
    target = '../bin/test_juce',
    use = [ 'LUA_objects', 'ELEMENT_APP_static', 'ELEMENT', 'LIBJUCE' ],
    install_path = None
))

progs.append (bld.program (
    source = bld.path.ant_glob ("*.cpp") + \
             bld.path.ant_glob ("scripting/*.cpp"),
    includes = [ '.' ],
    target = '../bin/test_element',
    use = [ 'ELEMENT_APP_static', 'LUA_objects', 'ELEMENT', 'LIBJUCE', 'BOOST_TEST' ],
    install_path = None
))

for p in progs:
    for k in 'CFLAGS CXXFLAGS LINKFLAGS'.split():
        p.env.append_unique (k, [ '-fvisibility=hidden' ])
