#!/usr/bin/env python

import inspect, os, sys
submodule_help  = "Are submodules up to date? Try 'git submodule update --init --recursive'\n"
waflib_path     = os.path.join (os.getcwd(), 'libs/waf')
sys.path.insert (0, waflib_path)
sys.path.insert (1, os.path.join (os.getcwd(), 'tools/waf'))

try:
    from waflib import Context, Scripting
except Exception as e:
    sys.stderr.write ('error: Failed to import waf (%s)\n' % e)
    if os.path.exists ('.git'):
        sys.stderr.write (submodule_help)
    sys.exit(1)

def main():
    Scripting.waf_entry_point(os.getcwd(), Context.WAFVERSION, waflib_path)

if __name__ == '__main__':
    main()
