#!/usr/bin/env python

bld.program (
    source = bld.path.ant_glob("**/*.cpp"),
    includes = ['.',
                '../libs/compat',
                '../libs/jlv2/modules',
                '../libs/JUCE/modules',
                '../libs/kv/modules',
                '../libs/lua/src',
                '../src' ],
    target = '../bin/test-element',
    use = [ 'FREETYPE2', 'X11', 'DL', 'PTHREAD', 
            'ALSA', 'XEXT', 'ELEMENT', 'PYTHON', 'LUA' ],
    install_path = None
)
