#!/usr/bin/env python

bld.program(
    source = bld.path.ant_glob("**/*.cpp"),
    includes = ['.', '../project/Source', '../project/JuceLibraryCode'],
    target = 'tests',
    use = 'JUCE_CORE',
    install_path = None
)
