#!/usr/bin/env python
# Build the unit tests

bld.program (
    source = bld.path.ant_glob ("**/*.cpp"),
    includes = [ '.' ],
    target = '../bin/test-element',
    use = [ 'ELEMENT', 'LUA' ],
    install_path = None
)
