#!/usr/bin/env python
# Builds the lua-el interpretor

lua_el = bld.program (
    source = [ 'lua.cpp' ],
    name = 'lua-el',
    target = '../../bin/lua-el',
    includes = [ '.', ],
    use = [ 'APP_objects', 'LUA_KV_objects', 'ELEMENT', 'READLINE', 'LIBJUCE' ],
    install_path = None,
    env = bld.env.derive()
)

for key in 'LINKFLAGS CFLAGS CXXFLAGS'.split():
    lua_el.env.append_unique (key, [ '-fvisibility=hidden'])
