#!/usr/bin/env python
# Builds the lua-el interpretor

bld.program (
    source = [ 'lua.cpp' ],
    name = 'lua-el',
    target = '../../bin/lua-el',
    includes = [ '.', ],
    use = [ 'APP_objects', 'LUA_KV_objects', 'ELEMENT', 'READLINE', 'LIBJUCE' ],
    install_path = None
)
