/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define EL_BUILD_NUMBER 384

#define EL_GIT_HASH "e9c54ab2c28d4a728c6a00df101e036223bcbec7"

#define EL_GIT_SHORT_HASH "e9c54ab2"

#define EL_VERSION_STRING "1.0.0"
